# my global config
global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
    monitor: 'codelab-monitor'
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'cqb-base-mgr-dev'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /cqb-base-mgr/prometheus
    scheme: http
    static_configs:
      - targets: ['cqb-gz.dev.sh-weiyi.com']
  - job_name: 'cqb-base-dev'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /cqb-base/prometheus
    scheme: http
    static_configs:
      - targets: ['cqb-gz.dev.sh-weiyi.com']
  - job_name: 'cqb-base-mgr-test'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /cqb-base-mgr/prometheus
    scheme: http
    static_configs:
      - targets: ['cqb-gz.test.sh-weiyi.com']
  - job_name: 'cqb-base-test'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /cqb-base/prometheus
    scheme: http
    static_configs:
      - targets: ['cqb-gz.test.sh-weiyi.com']
